sudo: true 
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm link
script:
  - npm run test:single
after_success:
  - npm run semantic-release
